
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tushu?useSSL=false&serverTimezone=GMT%2B8
    password: 12345678
    username: root

logging:
  level:
    root: debug
#自动下划线转驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true