
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tushu?useSSL=false&serverTimezone=GMT%2B8
    password: 12345678
    username: root


#logging:
#  level:
#    org:
#      apache:
#        ibatis:
#          binding: debug
#    @GeneratedValue(generator = "JDBC")debug
#  path: com.dzhou
logging:
  level:
    root: debug